# start backend apps
version: "3.9"
services:
  neo4j:
    image: "olympeio/neo4j-procedure:1.8.5"
    container_name: "neo4j"
    environment:
      NEO4J_AUTH: "neo4j/password1"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    ports:
      # Offer neo4j console for debugging
      - 7474:7474
      - 7687:7687
    volumes:
      - ./backend/neo4j-data:/data
      - ./backend/neo4j-logs:/log
  orchestrator:
    image: "olympeio/orchestrator:5.9.7"
    depends_on:
      - neo4j
      - rabbitmq
    container_name: "orchestrator"
    ports:
      - 8080:8080
    volumes:
      - ./backend/orchestrator/file-service:/opt/orchestrator/file-service
    environment:
      DB_HOSTNAME: neo4j
      DB_USER: neo4j
      DB_PASSWORD: password1
      WAIT_FOR_NEO4J: 120
      RABBITMQ_HOST: rabbitmq
      PERMISSION_CHECK_ENABLED: 'false'
  rabbitmq:
    build:
      context: ./docker
      dockerfile: ./rabbitmq.Dockerfile
    image: olympeio/rabbitmq:3.8
    container_name: rabbitmq
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 5s
      timeout: 10s
      retries: 50
    ports:
      - 15672:15672
      - 15675:15675
      - 5672:5672
